/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package EjerciciosS5;

import jade.gui.GuiAgent;
import jade.gui.GuiEvent;

/**
 *
 
 */
public class VentanaChat extends javax.swing.JFrame {

    GuiAgent owner;
    
    /**
     * Creates new form VentanaChat
     */
    public VentanaChat(GuiAgent p, String nagent) {
        initComponents();
        this.owner = p;
        this.jLabel1.setText(nagent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setForeground(new java.awt.Color(51, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setText("VENTANA CHAT");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(80, 10, 160, 20);

        jLabel2.setText("Nombre Agente");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(210, 10, 110, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 40);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(null);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 380, 210);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 40, 400, 230);

        jPanel3.setBackground(new java.awt.Color(153, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(null);

        jLabel3.setText("Mensaje");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(50, 30, 130, 20);

        jTextField1.setText("jTextField1");
        jPanel3.add(jTextField1);
        jTextField1.setBounds(190, -2, 190, 30);

        jLabel4.setText("Agente Recibe");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(50, 6, 130, 20);

        jTextField2.setText("jTextField2");
        jPanel3.add(jTextField2);
        jTextField2.setBounds(190, 28, 190, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 270, 400, 70);

        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(140, 340, 82, 29);

        jButton2.setText("Enviar TODOS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(240, 340, 131, 29);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.out.println(" Enviar mensaje ");
        
        GuiEvent  evento = new GuiEvent (this, 0);
        evento.addParameter(this.jTextField1.getText());
        evento.addParameter(this.jTextField2.getText());
        owner.postGuiEvent(evento);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        // configure el GuiEvent tome como ejemplo el anterior
        // GuiEvent  evento = new GuiEvent (this, 0);
        //evento.addParameter(this.jTextField1.getText());
        //evento.addParameter(this.jTextField2.getText());
        //owner.postGuiEvent(evento);
        // verifique si necesita todos los campos
        // debe tener en cuenta el Numero del parametro que va en el evento
        
    }//GEN-LAST:event_jButton2ActionPerformed

    public void escribirMensaje(String m)
    {
        this.jTextArea1.insert(m + "\n", 0);
    }
    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
